export const MEDICINE_DATABASE = [
  { name: "Metformin", dosages: ["500mg", "850mg", "1000mg"] },
  { name: "Amlodipine", dosages: ["2.5mg", "5mg", "10mg"] },
  { name: "Atorvastatin", dosages: ["10mg", "20mg", "40mg", "80mg"] },
  { name: "Lisinopril", dosages: ["5mg", "10mg", "20mg", "40mg"] },
  { name: "Omeprazole", dosages: ["10mg", "20mg", "40mg"] },
  { name: "Paracetamol", dosages: ["325mg", "500mg", "650mg", "1000mg"] },
  { name: "Ibuprofen", dosages: ["200mg", "400mg", "600mg", "800mg"] },
  { name: "Aspirin", dosages: ["75mg", "150mg", "325mg"] },
  { name: "Amoxicillin", dosages: ["250mg", "500mg", "875mg"] },
  { name: "Azithromycin", dosages: ["250mg", "500mg"] },
  { name: "Cetirizine", dosages: ["5mg", "10mg"] },
  { name: "Pantoprazole", dosages: ["20mg", "40mg"] },
  { name: "Losartan", dosages: ["25mg", "50mg", "100mg"] },
  { name: "Glimepiride", dosages: ["1mg", "2mg", "4mg"] },
  { name: "Levothyroxine", dosages: ["25mcg", "50mcg", "75mcg", "100mcg"] },
  { name: "Atenolol", dosages: ["25mg", "50mg", "100mg"] },
  { name: "Bisoprolol", dosages: ["2.5mg", "5mg", "10mg"] },
  { name: "Telmisartan", dosages: ["20mg", "40mg", "80mg"] },
  { name: "Rosuvastatin", dosages: ["5mg", "10mg", "20mg", "40mg"] },
  { name: "Clopidogrel", dosages: ["75mg"] },
  { name: "Ramipril", dosages: ["1.25mg", "2.5mg", "5mg", "10mg"] },
  { name: "Furosemide", dosages: ["20mg", "40mg", "80mg"] },
  { name: "Spironolactone", dosages: ["25mg", "50mg", "100mg"] },
  { name: "Digoxin", dosages: ["0.125mg", "0.25mg"] },
  { name: "Warfarin", dosages: ["1mg", "2mg", "5mg"] },
  { name: "Insulin Glargine", dosages: ["10 units", "20 units", "Custom"] },
  { name: "Insulin Regular", dosages: ["4 units", "6 units", "8 units", "Custom"] },
  { name: "Prednisolone", dosages: ["5mg", "10mg", "20mg", "40mg"] },
  { name: "Dexamethasone", dosages: ["0.5mg", "1mg", "4mg"] },
  { name: "Montelukast", dosages: ["4mg", "5mg", "10mg"] },
  { name: "Salbutamol", dosages: ["2mg", "4mg", "100mcg inhaler"] },
  { name: "Theophylline", dosages: ["100mg", "200mg", "300mg"] },
  { name: "Metoprolol", dosages: ["25mg", "50mg", "100mg"] },
  { name: "Valsartan", dosages: ["40mg", "80mg", "160mg", "320mg"] },
  { name: "Hydrochlorothiazide", dosages: ["12.5mg", "25mg", "50mg"] },
  { name: "Carvedilol", dosages: ["3.125mg", "6.25mg", "12.5mg", "25mg"] },
  { name: "Gabapentin", dosages: ["100mg", "300mg", "400mg"] },
  { name: "Pregabalin", dosages: ["25mg", "75mg", "150mg", "300mg"] },
  { name: "Sertraline", dosages: ["25mg", "50mg", "100mg"] },
  { name: "Escitalopram", dosages: ["5mg", "10mg", "20mg"] },
  { name: "Clonazepam", dosages: ["0.25mg", "0.5mg", "1mg", "2mg"] },
  { name: "Alprazolam", dosages: ["0.25mg", "0.5mg", "1mg"] },
  { name: "Diazepam", dosages: ["2mg", "5mg", "10mg"] },
  { name: "Pantoprazole", dosages: ["20mg", "40mg"] },
  { name: "Esomeprazole", dosages: ["20mg", "40mg"] },
  { name: "Rabeprazole", dosages: ["10mg", "20mg"] },
  { name: "Ondansetron", dosages: ["4mg", "8mg"] },
  { name: "Domperidone", dosages: ["10mg"] },
  { name: "Metoclopramide", dosages: ["5mg", "10mg"] },
  { name: "Loperamide", dosages: ["2mg"] },
  { name: "Lactulose", dosages: ["10g/15ml", "3.35g/5ml"] },
  { name: "Vitamin D3", dosages: ["400 IU", "1000 IU", "2000 IU", "5000 IU"] },
  { name: "Calcium Carbonate", dosages: ["500mg", "1000mg"] },
  { name: "Iron (Ferrous Sulphate)", dosages: ["65mg", "200mg"] },
  { name: "Folic Acid", dosages: ["0.4mg", "1mg", "5mg"] },
  { name: "Vitamin B12", dosages: ["500mcg", "1000mcg"] },
  { name: "Multivitamin", dosages: ["1 tablet"] },
  { name: "Zinc", dosages: ["10mg", "20mg", "50mg"] },
  { name: "Doxycycline", dosages: ["50mg", "100mg"] },
  { name: "Ciprofloxacin", dosages: ["250mg", "500mg", "750mg"] },
  { name: "Co-trimoxazole", dosages: ["480mg", "960mg"] },
  { name: "Clindamycin", dosages: ["150mg", "300mg"] },
  { name: "Fluconazole", dosages: ["50mg", "150mg"] },
  { name: "Acyclovir", dosages: ["200mg", "400mg", "800mg"] },
  { name: "Hydroxychloroquine", dosages: ["200mg", "400mg"] },
  { name: "Colchicine", dosages: ["0.5mg", "1mg"] },
  { name: "Allopurinol", dosages: ["100mg", "300mg"] },
  { name: "Febuxostat", dosages: ["40mg", "80mg"] },
  { name: "Naproxen", dosages: ["250mg", "500mg"] },
  { name: "Diclofenac", dosages: ["25mg", "50mg", "75mg", "100mg"] },
  { name: "Tramadol", dosages: ["50mg", "100mg"] },
  { name: "Codeine", dosages: ["15mg", "30mg"] },
  { name: "Tamsulosin", dosages: ["0.4mg"] },
  { name: "Finasteride", dosages: ["1mg", "5mg"] },
  { name: "Sildenafil", dosages: ["25mg", "50mg", "100mg"] },
  { name: "Clomiphene", dosages: ["50mg"] },
  { name: "Progesterone", dosages: ["100mg", "200mg"] },
];

export function searchMedicines(query) {
  if (!query || query.length < 2) return [];
  const q = query.toLowerCase();
  return MEDICINE_DATABASE.filter((m) => m.name.toLowerCase().startsWith(q)).slice(0, 8);
}

export function getDosagesForMedicine(name) {
  const med = MEDICINE_DATABASE.find((m) => m.name.toLowerCase() === name.toLowerCase());
  return med ? med.dosages : [];
}